### PR TITLE
fix: avoid infinite loop when hitting an inexistent route

### LINKED ISSUE #48: bug: when hashBasedNavigation is true and url route can't be found, apps become unresponsive
When hashBasedNavigation is true and a 404 link is pressed, there is an infinite update loop that makes the app go totally unresponsive.
To reproduce this just convert the UI folder of this repo to use the hashBasedNavigation and insert an inexistent link wherever you want and notice the behavior.

FYI: Right now links in markdown when hashBasedNavigation is true should start with an hashtag (`#/guides/whatever`), but the bug can be reproduced either way of course.

Check the screencast: 

https://github.com/user-attachments/assets/b4bcf1fe-4beb-4503-a6d5-8829ff16d9fe

Please notice the url which demonstrate I'm hitting an inexistent link.

Screenshot 2024-08-22 at 00 26 45

### PR DESCRIPTION
**Pull request by giacomocerquone**
closes #48 

## Testing the pr

When testing the pr, remember to
1. Add `ElmBook.ThemeOptions.useHashBasedNavigation` in the UI/ElmBook.elm file
2. Modify a chapter so to add an inexistent link to test the bugfix 

FYI: The links **must** be in this format `#/guides/inexistent`

## Rationale

When hashBasedNavigation is true and a route that can't be found among the chapters is hit, this is what happens:

1. OnUrlChange is triggered
2. `extractPath url_` is called and returns `/guides/inexistent` (url.fragment) which is then assigned to `url`
3. The catch all "\_" case executes
4. An urlChapter can't be found so it goes in the `Nothing` case
5. The `Nothing` case navigates to `#/`
6. The OnUrlChange is triggered again
7. `extractPath url_` is called and returns `/` (`url.fragment` is `Nothing` hence `Maybe.withDefault` kicks in) which is then assigned to `url`
8. The "\/" case executes
9. It gets the fallback chapter's url (`/overview` in the case of this repo) and navigates there, which is a problem because we have hashBasedNavigation set to true
10. The OnUrlChange is triggered again
11. `extractPath url_` is called and when hashBasedNavigation is true it returns the fragment or `/` and in the case of `/overview` the fragment is Nothing.
12. From now on it repeats from 8 to 12 infinitely 

Screenshot 2024-08-21 at 20 52 51

## Solution

How do we stop it? Should be simple honestly, when the fallback chapter is retrieved, let's add the hashtag on front.

### Screencast

https://github.com/user-attachments/assets/669b83f2-15fd-409f-9774-57412e7940c1

### CODE REVIEW

File: src/ElmBook/Internal/Application.elm [hunk 1]
```diff
@@ -346,6 +356,7 @@ update config msg model =
                     targetChapter =
                         if Array.isEmpty filteredChapters then
                             Nothing
+
```
Comment (giacomocerquone) [inline src/ElmBook/Internal/Application.elm:359]: default elm formatter added this

**Comment by giacomocerquone** [comment]
Pipe is failing because of this

image

**Comment by giacomocerquone** [comment]
Hey there @georgesboris would you kindly take a look at this?

**Comment by georgesboris** [comment]
Hey @giacomocerquone ! So sorry for taking so long to get around to this - thanks for fixing it!
I'm gonna push a release right now to make it available.

**Review by georgesboris — APPROVED** [review]

**Comment by giacomocerquone** [comment]
> Hey @giacomocerquone ! So sorry for taking so long to get around to this - thanks for fixing it! I'm gonna push a release right now to make it available.

Absolutely no worries, thanks for getting at it eventually.

I wanted to fix this btw, because I'd like to give a shot at integrating linkable heading anchors in elm-book
